name: orca
channels:
  - defaults
dependencies:
  - archspec
  - boost-cpp
  - brotli-python
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - charset-normalizer
  - conda
  - conda-content-trust
  - conda-libmamba-solver
  - conda-package-handling
  - conda-package-streaming
  - cryptography
  - distro
  - expat
  - fmt
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-anaconda
  - fonts-conda-ecosystem
  - freetype
  - fribidi
  - gdk-pixbuf
  - gettext
  - giflib
  - glib
  - glib-tools
  - graphite2
  - graphviz
  - gts
  - harfbuzz
  - icu
  - idna
  - jpeg
  - jsonpatch
  - jsonpointer
  - krb5
  - lcms2
  - lerc
  - libarchive
  - libboost
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libffi
  - libgd
  - libglib
  - libiconv
  - libmamba
  - libmambapy
  - libnghttp2
  - libpng
  - librsvg
  - libsolv
  - libssh2
  - libtiff
  - libtool
  - libwebp
  - libwebp-base
  - libxml2
  - llvm-openmp
  - lz4-c
  - menuinst
  - ncurses
  - nspr
  - nss
  - openjpeg
  - openssl
  - packaging
  - pango
  - pcre2
  - pip
  - pixman
  - platformdirs
  - pluggy
  - poppler
  - poppler-data
  - pybind11-abi
  - pycosat
  - pycparser
  - pygraphviz
  - pysocks
  - python
  - readline
  - reproc
  - reproc-cpp
  - requests
  - ruamel.yaml
  - setuptools
  - sqlite
  - tk
  - tqdm
  - truststore
  - tzdata
  - urllib3
  - wheel
  - xz
  - yaml-cpp
  - zlib
  - zstandard
  - zstd
  - pip:
      - absl-py
      - annotated-types
      - anyio
      - astunparse
      - gast
      - h11
      - httpcore
      - httpx
      - hunter
      - manhole
      - networkx
      - numpy
      - openai
      - pydantic
      - pydantic-core
      - python-dotenv
      - python-graphs
      - six
      - sniffio
      - tree-sitter
      - typing-extensions